// d3-layout-example/src/pages/histogram/histogram.jsx
import React, { useRef, useEffect } from 'react';
import styles from "./histogram.scss";
import { Link } from 'react-router-dom';
import * as d3 from 'd3';

function Histogram() {
  const chartArea = useRef();

  const width = 400;
  const height = 600;

  const padding = {
    top: 10,
    right: 40,
    bottom: 40,
    left: 40
  };

  const data = d3.range(1000).map(function () {
    return d3.randomBates(10)();
  });

  console.log(data);
  const xScale = d3.scaleLinear()
    .range([padding.left, width - padding.right]);


  const histogramData = d3.histogram()
    .domain(xScale.domain())
    .thresholds(xScale.ticks(10))(data);

  console.log(histogramData);


  const xAxis = d3.axisBottom()
    .scale(xScale)
    .ticks(10);
  const yScale = d3.scaleLinear()
    .domain([0, d3.max(histogramData,
      function (d) {
        return d.length;
      })])
    .range([height - padding.bottom, padding.top]);
  const yAxis = d3.axisLeft()
    .scale(yScale)
    .ticks(10);
  let color = d3.scaleOrdinal(d3.schemeCategory10)

  useEffect(() => {
    const svg = d3.select(chartArea.current)
      .append('svg')
      .attr('width', width)
      .attr('height', height)

    svg.append('g')
      .call(xAxis)
      .attr("transform", "translate(0," + (height - padding.bottom) + ")");

    svg.append('g')
      .call(yAxis)
      .attr("transform", "translate(" + padding.left + ",0)");

    const bar = svg.selectAll(".bar")
      .data(histogramData)
      .join("g")
      .attr("class", "bar")
      .attr("transform",
        function (d) {
          return "translate(" + xScale(d.x0) + "," + yScale(d.length) + ")";
        });
    // 构造柱
    bar.append("rect")
      .attr("x", 1)
      .attr('fill', (d, i) => color(i))
      .attr("width", xScale(histogramData[0].x1) - xScale(histogramData[0].x0) - 1)
      .attr("height",
        function (d) {
          return height - yScale(d.length) - padding.bottom;
        });

    bar.append("text")
      .attr("dy", ".75em")
      .attr("y", 6)
      .attr("x", (xScale(histogramData[0].x1) - xScale(histogramData[0].x0)) / 2)
      .attr("text-anchor", "middle")
      .attr("font-size", "8px")
      .attr("fill", "White")
      .text(function (d) {
        return d.length;
      });
  }, [color, histogramData, padding.bottom, padding.left, xAxis, xScale, yAxis, yScale])



  return (
    [<div key={'histogram'} ref={chartArea} className={styles.page}></div>, <Link key={'link'} to={'/'}>返回</Link>]
  );
}
export default Histogram;

// docs/.vuepress/components/Demo/Histogram.vue
<template>
  <div ref="svgBox" class="svgBox"></div>
</template>
<script>
import * as d3 from "d3";
import { getDefauteParams } from "./utils";
export default {
  data() {
    return {
      //输入
      oriData: d3.range(1000).map(function() {
        return d3.randomBates(10)();
      })
    };
  },
  methods: {
    layout() {
      this.xScale = d3
        .scaleLinear()
        .range([this.padding.left, this.width - this.padding.right]);

      this.layouter = d3
        .histogram()
        .domain(this.xScale.domain())
        .thresholds(this.xScale.ticks(10));

      this.layoutData = this.layouter(this.oriData);

      this.yScale = d3
        .scaleLinear()
        .domain([
          0,
          d3.max(this.layoutData, function(d) {
            return d.length;
          })
        ])
        .range([this.height - this.padding.bottom, this.padding.top]);
      this.xAxis = d3
        .axisBottom()
        .scale(this.xScale)
        .ticks(10);
      this.yAxis = d3
        .axisLeft()
        .scale(this.yScale)
        .ticks(10);
    },
    render() {
      const svg = d3
        .select(this.dom)
        .append("svg")
        .attr("width", this.width)
        .attr("height", this.height);
      svg
        .append("g")
        .call(this.xAxis)
        .attr(
          "transform",
          "translate(0," + (this.height - this.padding.bottom) + ")"
        )
        .attr("color", "White");

      svg
        .append("g")
        .call(this.yAxis)
        .attr("transform", "translate(" + this.padding.left + ",0)")
        .attr("color", "White");
        
      const bar = svg
        .selectAll(".bar")
        .data(this.layoutData)
        .join("g")
        .attr("class", "bar")
        .attr("transform", d => {
          return (
            "translate(" + this.xScale(d.x0) + "," + this.yScale(d.length) + ")"
          );
        });

      // 构造柱
      bar
        .append("rect")
        .attr("x", 1)
        .attr("fill", (d, i) => this.color(i))
        .attr(
          "width",
          this.xScale(this.layoutData[0].x1) -
            this.xScale(this.layoutData[0].x0) -
            1
        )
        .attr("height", d => {
          return this.height - this.yScale(d.length) - this.padding.bottom;
        });

      bar
        .append("text")
        .attr("dy", ".75em")
        .attr("y", 6)
        .attr(
          "x",
          (this.xScale(this.layoutData[0].x1) -
            this.xScale(this.layoutData[0].x0)) /
            2
        )
        .attr("text-anchor", "middle")
        .attr("font-size", "20px")
        .attr("fill", "White")
        .text(function(d) {
          return d.length;
        });
    }
  },
  mounted() {
    getDefauteParams.bind(this)();
    this.layout();
    this.render();
  }
};
</script>
<style lang="less" scoped>
.svgBox {
  width: 100%;
  height: 300px;
  background: rgb(40, 44, 52);
}
</style>
