// d3-layout-example/src/pages/pack/pack.jsx
import React, { useRef, useEffect } from 'react';
import styles from "./pack.scss";
import { Link } from 'react-router-dom';
import * as d3 from 'd3';
import hierarchyData from '../../components/hierarchy';

function Pack() {
  const chartArea = useRef();

  const width = 400;
  const height = 600;

  console.log(hierarchyData);
  const packData = d3.pack()
    .size([width, height])(hierarchyData).descendants();
  console.log(packData);


  let color = d3.scaleOrdinal(d3.schemeCategory10)

  useEffect(() => {
    const svg = d3.select(chartArea.current)
      .append('svg')
      .attr('width', width)
      .attr('height', height)

    const nodes = svg.selectAll('.node')
      .data(packData)
      .enter()
      .append('g')
      .attr('transform', d => "translate(" + d.x + "," + d.y + ")")
      .attr('class', 'node')

    nodes.append("circle")
      .attr('fill', (d, i) => color(i))
      .attr("r", d => d.r);

    nodes.append('text')
      .text((d) => { if (!d.children) return d.data.name })
      .attr('font-size', (d) => { return 14 - d.depth + 'px' })
      .attr('text-anchor', "middle")
      .attr('dominant-baseline', "middle")
      .attr('fill', '#ffffff')

  }, [color, packData])



  return (
    [<div key={'pack'} ref={chartArea} className={styles.page}></div>, <Link key={'link'} to={'/'}>返回</Link>]
  );
}
export default Pack;

// docs/.vuepress/components/Demo/Pack.vue
<template>
  <div ref="svgBox" class="svgBox"></div>
</template>
<script>
import * as d3 from "d3";
import { getDefauteParams } from "./utils";
import nodeData from "./Hierarchy";

export default {
  data() {
    return {};
  },
  methods: {
    layout() {
      this.layouter = d3.pack().size([this.width, this.height]);
      // 输出
      this.layoutData = this.layouter(nodeData).descendants();
      console.log(this.layouter(nodeData))
    },
    render() {
      const svg = d3
        .select(this.dom)
        .append("svg")
        .attr("width", this.width)
        .attr("height", this.height);

      const nodes = svg
        .selectAll(".node")
        .data(this.layoutData)
        .enter()
        .append("g")
        .attr("transform", d => "translate(" + d.x + "," + d.y + ")")
        .attr("class", "node");

      nodes
        .append("circle")
        .attr("fill", (d, i) => this.color(i))
        .attr("r", d => d.r);

      nodes
        .append("text")
        .text(d => {
          if (!d.children) return d.data.name;
        })
        .attr("font-size", d => {
          return 14 - d.depth + "px";
        })
        .attr("text-anchor", "middle")
        .attr("dominant-baseline", "middle")
        .attr("fill", "#ffffff");
    }
  },
  mounted() {
    getDefauteParams.bind(this)();
    this.layout();
    this.render();
  }
};
</script>
<style lang="less" scoped>
.svgBox {
  width: 100%;
  height: 300px;
  background: rgb(40, 44, 52);
}
</style>
